---

stages:
  - deploy

build-package:
  tags:
    - docker-gcc
  stage: deploy
  image: python:3.7
  script:
    - cat $PYPIRC > /tmp/.pypirc
    - pip install twine build
    - python -m build
    - python -m twine upload --repository testpypi dist/guacamole_api_wrapper-${CI_COMMIT_TAG}-py3-none-any.whl --config-file /tmp/.pypirc
  only:
    - tags
