---

stages:
  - test
  - deploy

build-package:
  tags:
    - docker-gcc
  stage: test
  image: python:latest
  script:
    - mv $(echo $pypirc) /root/.pypirc
    - pip install twine build
    - python -m build
    - python -m twine upload --repository testpypi dist/*
  only:
    - tags
  allow_failure: true

test-package:
  tags:
    - docker-gcc
  stage: test
  image: python:latest
  script:
    - pip install -i https://test.pypi.org/simple/ guacamole-api-wrapper
    - echo ' future testing put here'
  dependencies:
    - build-package
  only:
    - tags
  allow_failure: true

deploy-package:
  tags:
    - docker-gcc
  stage: deploy
  image: python:latest
  script:
    - mv $(echo $pypirc) /root/.pypirc
    - pip install twine build
    - python -m build
    - python -m twine upload --repository gitlab dist/*
    - python -m twine upload --repository pypi dist/*
  dependencies:
    - test-package
  only:
    - tags