---

stages:
  - deploy

build-package:
  tags:
    - docker-gcc
  stage: deploy
  image: python:latest
  script:
    - echo $PYPIRC
    # - cat $PYPIRC > /tmp/.pypirc
    # - pip install twine build
    # - python -m build
    # - python -m twine upload --repository testpypi dist/* --config-file /tmp/.pypirc
  only:
    - tags
