---

stages:
  - deploy

build-package:
  tags:
    - docker-gcc
  stage: deploy
  image: python:latest
  script:
    - mv $(echo $pypirc) /root/.pypirc
    - pip install twine build
    - python -m build
    - python -m twine upload --repository testpypi dist/*
  only:
    - tags
