---

stages:
  - deploy

build-package:
  tags:
    - docker-gcc
  stage: deploy
  image: python:latest
  script:
    - pip install twine build
    - python -m build
    - python -m twine upload --repository testpypi dist/* --config-file /builds/gacybercenter/gacyberrange/projects/guacamole-api-wrapper.tmp/pypirc
  only:
    - tags
